version: '3.1'
services:
  stats-server:
    build: ./ewm-stats/stat-server
    image: ewm-stat-server
    container_name: ewm-stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-statistics-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ./ewm-main
    image: ewm-main-service
    container_name: ewm-main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - STATS-SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-main
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
